# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Hiromichi Kamata
# Description of the Site
description: An AI RESEARCHER
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Hiromichi Kamata, Spiking Neural Network, AI, Fully Spiking Variational Autoencoder, University of Tokyo
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/hero.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kamata@mi.t.u-tokyo.ac.jp
facebook_username: 
twitter_username: ChagallBlau
instagram_username: 
linkedin_username: hiromichi-kamata-10a736186
github_username:  kamata1729
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-221388672-1

# Disqus
disqus-shortname: 

# Name of the Author
author-name: HiromichiKamata
# URL for the Image of the Author
author-image: https://i.imgur.com/OqGecyy.jpg
#author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: I'm Hiromichi Kamata (鎌田啓路), a master course student of <a href= "https://www.mi.t.u-tokyo.ac.jp/" >Harada-Mukuta lab</a> at the University of Tokyo. My research interests are Spiking Neural Networks (SNN), accelerating Neural Networks, speech recognitions, etc.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/kamata1729

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
